### ISSUE TITLE
Unexpected copyright text for images

### ISSUE THREAD

**Issue by yoshih** [denkungsart/chat_noir#4]
On Castupload I worked with the blog (post from link). When I paste a link from an actor profile, the copyright text below the picture contains the address of the agency. So it seems like there is taken some random content from the page. Maybe we should return just `nil` when no copyright information is found.

**Comment by shiroginne** [comment]
Could you send a link which returns this address? I'll try to see what could be done here

**Comment by yoshih** [comment]
https://www.castupload.com/actors/adrian-topol

It returns this content as copyright:
![Bildschirmfoto 2019-03-22 um 10 08 34](https://user-images.githubusercontent.com/28568704/54812063-7f82ff00-4c8a-11e9-91b7-69cd64fc32f8.png)

**Comment by shiroginne** [comment]
Ok, I've fixed it:
```ruby
 :001 > ChatNoir.copyright("https://www.castupload.com/actors/adrian-topol")
 => "Michael Schuff" 
```

**Comment by shiroginne** [comment]
Please, update gem in projects which depend on it
